const credentials = [
  {code:'FP-01',category:'Fall protection & rescue',title:'Competent Climber / Rescuer',desc:'Third-party hands-on climber and rescue qualification.',status:'complete',label:'Accepted',issuer:'Safety LMS / ComTrain',delivery:'Hands-on',standard:'NATE CRTS',expires:'Oct 2026',rule:'Require independent issuer, hands-on skills evaluation, named evaluator or instructor, current dates, and documented fall-protection and rescue scope.'},
  {code:'RG-02',category:'Rigging',title:'Competent Rigging',desc:'Load handling, signaling, inspection, and rigging practices.',status:'complete',label:'Accepted',issuer:'Safety LMS / ComTrain',delivery:'Hands-on',standard:'A10.48',expires:'Oct 2026',rule:'Verify role-appropriate rigging scope, qualified instructor, completion date, expiration, and third-party issuer.'},
  {code:'HO-03',category:'Hoisting',title:'Capstan Hoist Operations',desc:'Telecom capstan setup, operation, and hazard controls.',status:'complete',label:'Accepted',issuer:'Safety LMS / ComTrain',delivery:'Practical',standard:'A10.48',expires:'Oct 2026',rule:'Require telecom-specific capstan content, third-party issuer, credential identifier, and current expiration.'},
  {code:'RF-04',category:'RF safety',title:'RF / EMF Awareness',desc:'Radio-frequency exposure recognition and controls.',status:'complete',label:'Accepted',issuer:'Safety LMS / ComTrain',delivery:'Online allowed',standard:'A10.48',expires:'Oct 2026',rule:'Verify RF/EMF scope, named learner, independent issuer, issue date, and current expiration.'},
  {code:'FA-05',category:'Emergency medical',title:'First Aid / CPR / AED',desc:'Current blended or classroom credential with skills check.',status:'complete',label:'Accepted',issuer:'ProTrainings',delivery:'Blended + skills',standard:'OSHA 1926.50',expires:'Oct 2026',rule:'HARD GATE: Reject wholly online training. Require in-person skills evaluation, named evaluator, verifiable third-party issuer, and valid certificate.'},
  {code:'ME-06',category:'Powered access',title:'MEWP Operator',desc:'Operator training with practical evaluation.',status:'complete',label:'Accepted',issuer:'Sunbelt Rentals',delivery:'Practical',standard:'OSHA 1926',expires:'Nov 2027',rule:'Require third-party operator course, practical evaluation, trainer identification, and expiration date.'},
  {code:'OS-07',category:'Construction safety',title:'OSHA 30 Construction',desc:'Authorized OSHA Outreach construction credential.',status:'complete',label:'Accepted',issuer:'OSHA Outreach provider',delivery:'Authorized',standard:'OSHA 1926',expires:'No expiry',rule:'Verify OSHA Outreach card/course, trainer or provider authenticity, learner identity, and completion date.'},
  {code:'HC-08',category:'Hazard communication',title:'HazCom / GHS',desc:'Hazard communication and chemical labeling awareness.',status:'complete',label:'Accepted',issuer:'Safety LMS / ComTrain',delivery:'Online allowed',standard:'OSHA 1926.59',expires:'Oct 2026',rule:'Third-party online delivery may be accepted if content, identity, issue date, and verification evidence are present.'},
  {code:'BB-09',category:'Occupational health',title:'Bloodborne Pathogens',desc:'Exposure-control and universal-precautions training.',status:'finding',label:'Renew soon',issuer:'ProTrainings',delivery:'Online allowed',standard:'OSHA',expires:'Oct 2026',rule:'Verify current third-party certificate and applicable exposure-control content. Flag inside the configured renewal window.'},
  {code:'NW-10',category:'Industry credential',title:'NWSA TTT1',desc:'Telecommunications Tower Technician 1 credential.',status:'complete',label:'Accepted',issuer:'NWSA',delivery:'Exam + practical',standard:'NWSA / NATE',expires:'Verify registry',rule:'Require official third-party credential verification. Registry status controls acceptance when the document has no clear expiration.'}
];

let selected=0;
const $=id=>document.getElementById(id), list=$('controlList');
function render(){
 list.innerHTML=credentials.map((c,i)=>`<div class="control-item ${c.status} ${i===selected?'active':''}" data-index="${i}" tabindex="0" role="button"><span class="control-check">${c.status==='complete'?'✓':'!'}</span><div class="control-copy"><small>${c.code} · ${c.category.toUpperCase()}</small><strong>${c.title}</strong><p>${c.issuer} · ${c.delivery} · Expires ${c.expires}</p></div><span class="control-status ${c.status}">${c.label}</span></div>`).join('');
 list.querySelectorAll('.control-item').forEach(el=>{const go=()=>select(+el.dataset.index);el.onclick=go;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')go()}});
}
function select(i){selected=i;const c=credentials[i];$('detailCode').textContent=c.code;$('detailCategory').textContent=c.category.toUpperCase();$('detailTitle').textContent=c.title;$('detailDescription').textContent=c.desc;$('detailRequirement').textContent=c.rule;$('detailStatus').textContent=c.label;$('detailStatus').className=`status-pill ${c.status}`;document.querySelector('.gate-strip').innerHTML=`<span>3RD PARTY</span><b>Required</b><span>DELIVERY</span><b>${c.delivery}</b><span>STANDARD</span><b>${c.standard}</b>`;$('evidenceList').innerHTML=`<div class="evidence-item"><span class="file-icon pdf">CERT</span><div><strong>${c.title} certificate</strong><small>${c.issuer} · Expires ${c.expires}</small></div><button type="button">•••</button></div><div class="evidence-item"><span class="file-icon doc">${c.status==='complete'?'PASS':'FLAG'}</span><div><strong>AI validation</strong><small>${c.status==='complete'?'Third-party and core evidence gates passed':'Renewal or registry follow-up required'}</small></div><button type="button">•••</button></div>`;$('reviewNotes').value=`AI reviewed issuer independence, employee identity, course scope, delivery method, dates, and verification evidence against ${c.standard}.`;$('agentVerdict').textContent=c.status==='complete'?'COMPLIANT':'ACTION REQUIRED';$('agentReason').textContent=c.status==='complete'?'All mandatory evidence gates passed.':'Credential needs renewal or registry verification.';document.querySelector('.agent-verdict').classList.toggle('flag',c.status!=='complete');document.querySelector('.agent-verdict>span').textContent=c.status==='complete'?'✓':'!';document.querySelector('.review-panel').classList.remove('closed');render()}
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2400)}
$('runReview').onclick=()=>toast('AI review complete — 10 certificates analyzed');$('newReview').onclick=()=>toast('Certificate upload intake ready');$('closeReview').onclick=()=>document.querySelector('.review-panel').classList.add('closed');$('addEvidence').onclick=()=>toast('Certificate upload intake ready');
$('exportBtn').onclick=()=>{const report=`TELECOM CERTIFICATION AUDIT\nEmployee: T. Anderson\nRule set: ANSI/ASSP A10.48-2023 | OSHA 29 CFR 1926 | ANSI/ASSP Z359 | NATE CRTS\n\nPOLICY GATES\n- Third-party training only; in-house training rejected\n- First Aid/CPR must include in-person skills evaluation; online-only rejected\n\n${credentials.map(c=>`${c.code} | ${c.title} | ${c.label} | ${c.issuer} | ${c.expires}`).join('\n')}\n\nDecision-support record; final employer verification required.`;const url=URL.createObjectURL(new Blob([report],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='TC-2026-0711-audit.txt';a.click();URL.revokeObjectURL(url);toast('Audit exported')};
render();
