const credentials = [
  {code:'CL-01',category:'Work at heights',title:'Authorized or Competent Climber',desc:'One current third-party climber qualification is required.',status:'complete',label:'Height gate passed',issuer:'Safety LMS / ComTrain',delivery:'Hands-on',standard:'NATE CRTS',expires:'Oct 2026',gate:'heights',rule:'HEIGHT GATE: Accept either Authorized Climber or Competent Climber. Require an independent issuer, hands-on skills evaluation, named evaluator or instructor, and current dates.'},
  {code:'CR-02',category:'Work at heights',title:'Climber Rescue',desc:'Current hands-on tower rescue qualification is required.',status:'complete',label:'Height gate passed',issuer:'Safety LMS / ComTrain',delivery:'Hands-on',standard:'NATE CRTS',expires:'Oct 2026',gate:'heights',rule:'HEIGHT GATE: Require current third-party Climber Rescue training with hands-on rescue evaluation. A combined Climber/Rescuer certificate may satisfy both height gates when both scopes are documented.'},
  {code:'OS-03',category:'Site access',title:'OSHA 10 or OSHA 30 Construction',desc:'Either authorized OSHA Outreach credential satisfies this gate.',status:'complete',label:'Site gate passed',issuer:'OSHA Outreach provider',delivery:'Authorized',standard:'OSHA 1926',expires:'No expiry',gate:'site',rule:'SITE GATE: Require either OSHA 10 Construction or OSHA 30 Construction. Verify the Outreach card or provider, learner identity, and completion date.'},
  {code:'HC-04',category:'Site access',title:'HazCom / GHS',desc:'Hazard communication and chemical labeling awareness.',status:'complete',label:'Site gate passed',issuer:'Safety LMS / ComTrain',delivery:'Online allowed',standard:'OSHA 1926.59',expires:'Oct 2026',gate:'site',rule:'SITE GATE: Require current third-party HazCom training with learner identity, course scope, issue date, and verification evidence.'},
  {code:'BB-05',category:'Site access',title:'Bloodborne Pathogens',desc:'Exposure-control and universal-precautions training.',status:'finding',label:'Valid - renew soon',issuer:'ProTrainings',delivery:'Online allowed',standard:'OSHA',expires:'Oct 2026',gate:'site',valid:true,rule:'SITE GATE: Require a current third-party Bloodborne Pathogens certificate. A renewal warning does not fail access until the credential expires.'},
  {code:'RF-06',category:'Site access',title:'RF Safety',desc:'Radio-frequency exposure recognition and controls.',status:'complete',label:'Site gate passed',issuer:'Safety LMS / ComTrain',delivery:'Online allowed',standard:'A10.48',expires:'Oct 2026',gate:'site',rule:'SITE GATE: Require current RF Safety training from an independent third party, with named learner, course scope, issue date, and verification evidence.'},
  {code:'FA-07',category:'Site access',title:'First Aid / CPR / AED',desc:'Current blended or classroom credential with skills check.',status:'complete',label:'Site gate passed',issuer:'ProTrainings',delivery:'Blended + skills',standard:'OSHA 1926.50',expires:'Oct 2026',gate:'site',rule:'SITE HARD GATE: Reject wholly online training. Require in-person skills evaluation, named evaluator, verifiable third-party issuer, and a valid certificate.'},
  {code:'RG-08',category:'Task specific',title:'Competent Rigging',desc:'Required when assigned rigging responsibilities.',status:'complete',label:'Task qualified',issuer:'Safety LMS / ComTrain',delivery:'Hands-on',standard:'A10.48',expires:'Oct 2026',gate:'task',rule:'TASK GATE: Require for employees assigned rigging work. Verify role-appropriate scope, qualified instructor, completion date, expiration, and third-party issuer.'},
  {code:'HO-09',category:'Task specific',title:'Capstan Hoist Operations',desc:'Required when operating or working with a capstan hoist.',status:'complete',label:'Task qualified',issuer:'Safety LMS / ComTrain',delivery:'Practical',standard:'A10.48',expires:'Oct 2026',gate:'task',rule:'TASK GATE: Require for capstan operations. Verify telecom-specific content, third-party issuer, credential identifier, and current expiration.'},
  {code:'ME-10',category:'Task specific',title:'MEWP Operator',desc:'Required when assigned to operate a mobile elevating work platform.',status:'complete',label:'Task qualified',issuer:'Sunbelt Rentals',delivery:'Practical',standard:'OSHA 1926',expires:'Nov 2027',gate:'task',rule:'TASK GATE: Require for MEWP operators. Verify third-party operator course, practical evaluation, trainer identification, and expiration date.'},
  {code:'NW-11',category:'Industry credential',title:'NWSA TTT1',desc:'Additional telecommunications technician credential.',status:'complete',label:'Verified',issuer:'NWSA',delivery:'Exam + practical',standard:'NWSA / NATE',expires:'Verify registry',gate:'additional',rule:'Verify official third-party credential status in the registry when the document has no clear expiration.'}
];

let selected=0;
const $=id=>document.getElementById(id), list=$('controlList');
const isValid=c=>c.status==='complete'||c.valid===true;
function render(){
  list.innerHTML=credentials.map((c,i)=>`<div class="control-item ${c.status} ${i===selected?'active':''}" data-index="${i}" tabindex="0" role="button"><span class="control-check">${isValid(c)?'&#10003;':'!'}</span><div class="control-copy"><small>${c.code} &middot; ${c.category.toUpperCase()}</small><strong>${c.title}</strong><p>${c.issuer} &middot; ${c.delivery} &middot; Expires ${c.expires}</p></div><span class="control-status ${c.status}">${c.label}</span></div>`).join('');
  list.querySelectorAll('.control-item').forEach(el=>{const go=()=>select(+el.dataset.index);el.onclick=go;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')go()}});
}
function select(i){
  selected=i;const c=credentials[i],valid=isValid(c);
  $('detailCode').textContent=c.code;$('detailCategory').textContent=c.category.toUpperCase();$('detailTitle').textContent=c.title;$('detailDescription').textContent=c.desc;$('detailRequirement').textContent=c.rule;$('detailStatus').textContent=c.label;$('detailStatus').className=`status-pill ${c.status}`;
  document.querySelector('.gate-strip').innerHTML=`<span>3RD PARTY</span><b>Required</b><span>DELIVERY</span><b>${c.delivery}</b><span>GATE</span><b>${c.gate.toUpperCase()}</b>`;
  $('evidenceList').innerHTML=`<div class="evidence-item"><span class="file-icon pdf">CERT</span><div><strong>${c.title} certificate</strong><small>${c.issuer} &middot; Expires ${c.expires}</small></div><button type="button">&bull;&bull;&bull;</button></div><div class="evidence-item"><span class="file-icon doc">${valid?'PASS':'FLAG'}</span><div><strong>AI validation</strong><small>${valid?'Required evidence gate passed':'Missing, expired, or unverifiable credential'}</small></div><button type="button">&bull;&bull;&bull;</button></div>`;
  $('reviewNotes').value=`AI reviewed issuer independence, employee identity, course scope, delivery method, dates, and verification evidence against ${c.standard}.`;$('agentVerdict').textContent=valid?'COMPLIANT':'NOT ELIGIBLE';$('agentReason').textContent=valid?'The applicable credential gate is satisfied.':'This credential blocks the applicable work eligibility gate.';document.querySelector('.agent-verdict').classList.toggle('flag',!valid);document.querySelector('.agent-verdict>span').textContent=valid?'\u2713':'!';document.querySelector('.review-panel').classList.remove('closed');render();
}
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2400)}
$('runReview').onclick=()=>toast('AI review complete - site and height gates evaluated');$('newReview').onclick=()=>toast('Certificate upload intake ready');$('closeReview').onclick=()=>document.querySelector('.review-panel').classList.add('closed');$('addEvidence').onclick=()=>toast('Certificate upload intake ready');
$('exportBtn').onclick=()=>{const report=`C.O.R.E. TELECOM CERTIFICATION AUDIT\nEmployee: T. Anderson\n\nSITE ACCESS GATE\nOSHA 10 or 30 | HazCom | Bloodborne Pathogens | RF Safety | First Aid/CPR\n\nWORK-AT-HEIGHTS GATE\nAll site credentials | Authorized or Competent Climber | Climber Rescue\n\nPOLICY\nThird-party training only. In-house training rejected. Online-only First Aid/CPR rejected.\n\n${credentials.map(c=>`${c.code} | ${c.title} | ${c.label} | ${c.issuer} | ${c.expires}`).join('\n')}`;const url=URL.createObjectURL(new Blob([report],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='CORE-telecom-eligibility-audit.txt';a.click();URL.revokeObjectURL(url);toast('Audit exported')};
render();
